CREATE TABLE BookRoom(
id	NUMBER(6) PRIMARY KEY,
name	VARCHAR2(20) NOT NULL,
address	VARCHAR2(20),	
phone	VARCHAR2(20)
);




CREATE TABLE BookCatagory(
id	NUMBER(6) PRIMARY KEY,
name	VARCHAR2(20) NOT NULL,
brid	NUMBER(6) REFERENCES bookroom(id),
demo	VARCHAR2(100)
)



CREATE TABLE Book(
ISBN	VARCHAR2(20) PRIMARY KEY,
cid NUMBER(6) REFERENCES bookcatagory(id),
name	VARCHAR2(100) NOT NULL,
publish	VARCHAR2(20),	
author	VARCHAR2(20),	
publishDate DATE,	
price	NUMBER(6,2),	
storageDate	DATE,		
stockNumber	NUMBER,		
inNumber	NUMBER	
);

CREATE TABLE BookAdministrator(
id	VARCHAR2(20) PRIMARY KEY,
name	VARCHAR2(10),	
phone	VARCHAR2(10),	
brid	NUMBER(6) REFERENCES bookroom(id)
);





CREATE TABLE Reader(
id	VARCHAR2(20) PRIMARY KEY,
name	VARCHAR2(20) NOT NULL,
sex	CHAR(2) CHECK(sex IN ('ÄÐ','Å®')),	
phone	VARCHAR2(20),	
photo	VARCHAR2(20)	
);

	
CREATE TABLE BorrowLevel(
id	 NUMBER(2) PRIMARY KEY,
quantity NUMBER(6) DEFAULT 10,
days     NUMBER DEFAULT 30,
fine     NUMBER(6,2) DEFAULT 0.1,
demo	 VARCHAR2(100)
)



CREATE TABLE BorrowCard(
id	 VARCHAR2(20) PRIMARY KEY,
rid VARCHAR2(20) REFERENCES reader(id),
quantity NUMBER(6),	
blid	 NUMBER(2) REFERENCES borrowlevel(id)
);



CREATE TABLE Borrow(
id NUMBER PRIMARY KEY,
bcid	VARCHAR2(20)REFERENCES borrowcard(id),
ISBN	VARCHAR2(20)REFERENCES book(ISBN),
borrowDate DATE NOT NULL,
expireDate DATE,
dueDate DATE
);

CREATE TABLE Ticket(
id	NUMBER(6) PRIMARY KEY,
bcid	VARCHAR2(20) REFERENCES borrowcard(id),
isbn   VARCHAR2(20) REFERENCES book(ISBN),
fineMoney NUMBER(6,2),	
fineDate DATE
);

CREATE SEQUENCE seq_BookRoom START WITH 1 INCREMENT BY 1 NOCACHE;	
CREATE SEQUENCE seq_BookCatagory START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_BookAdministrator START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_Reader START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_BorrowCard START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_BorrowLevel START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_borrow START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_ticket START WITH 1 INCREMENT BY 1 NOCACHE;

